// Code generated by protoc-gen-go.
// source: grace.proto
// DO NOT EDIT!

/*
Package grace is a generated protocol buffer package.

It is generated from these files:
	grace.proto

It has these top-level messages:
	SleepRequest
	SleepResponse
*/
package grace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SleepRequest struct {
	Duration uint64 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *SleepRequest) Reset()                    { *m = SleepRequest{} }
func (m *SleepRequest) String() string            { return proto.CompactTextString(m) }
func (*SleepRequest) ProtoMessage()               {}
func (*SleepRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SleepRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type SleepResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *SleepResponse) Reset()                    { *m = SleepResponse{} }
func (m *SleepResponse) String() string            { return proto.CompactTextString(m) }
func (*SleepResponse) ProtoMessage()               {}
func (*SleepResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SleepResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*SleepRequest)(nil), "grace.SleepRequest")
	proto.RegisterType((*SleepResponse)(nil), "grace.SleepResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Demo service

type DemoClient interface {
	Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	out := new(SleepResponse)
	err := grpc.Invoke(ctx, "/grace.Demo/Sleep", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Demo service

type DemoServer interface {
	Sleep(context.Context, *SleepRequest) (*SleepResponse, error)
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grace.Demo/Sleep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Sleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grace.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sleep",
			Handler:    _Demo_Sleep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grace.proto",
}

func init() { proto.RegisterFile("grace.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4a, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xb4, 0xb8, 0x78, 0x82,
	0x73, 0x52, 0x53, 0x0b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x52,
	0x4a, 0x8b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0xe0, 0x7c,
	0x25, 0x79, 0x2e, 0x5e, 0xa8, 0xda, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6,
	0xfc, 0x6c, 0xb0, 0x32, 0x8e, 0x20, 0xa6, 0xfc, 0x6c, 0x23, 0x2b, 0x2e, 0x16, 0x97, 0xd4, 0xdc,
	0x7c, 0x21, 0x23, 0x2e, 0x56, 0xb0, 0x42, 0x21, 0x61, 0x3d, 0x88, 0x95, 0xc8, 0x56, 0x48, 0x89,
	0xa0, 0x0a, 0x42, 0xcc, 0x4a, 0x62, 0x03, 0x3b, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x12,
	0xc4, 0x54, 0xbf, 0xa5, 0x00, 0x00, 0x00,
}
